version: 2

multi-ecosystem-groups:
  monthly-dependencies:
    schedule:
      interval: monthly
    labels:
      - dependencies

updates:
  - package-ecosystem: gomod
    directories:
      - /
      - /platform
    patterns: ["*"]
    multi-ecosystem-group: monthly-dependencies
  - package-ecosystem: npm
    directory: /apps/web
    patterns: ["*"]
    multi-ecosystem-group: monthly-dependencies
  - package-ecosystem: docker
    directory: /platform
    patterns: ["*"]
    multi-ecosystem-group: monthly-dependencies
  - package-ecosystem: github-actions
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: monthly-dependencies
