package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

const schemaDirectory = "schemas/assets"

var targets = map[string]func([]AssetSchema) ([]byte, error){
	"platform/internal/assetschema/schema_gen.go":          generateGo,
	"api/generated/assets.schemas.yaml":                    generateOpenAPI,
	"apps/web/src/generated/assets.ts":                     generateTypeScript,
	"apps/web/src/generated/asset-meta.ts":                 generateVueMetadata,
	"deploy/postgres/migrations/asset/001_generated.sql":   generateSQL,
	"platform/internal/asset/migrations/001_generated.sql": generateSQL,
}

func main() {
	write := flag.Bool("write", false, "write generated artifacts")
	check := flag.Bool("check", false, "fail when generated artifacts are stale")
	flag.Parse()
	if *write == *check {
		fatalf("choose exactly one of -write or -check")
	}
	schemas, err := loadSchemas(schemaDirectory)
	if err != nil {
		fatalf("load schemas: %v", err)
	}
	for _, target := range sortedTargets() {
		generated, err := targets[target](schemas)
		if err != nil {
			fatalf("generate %s: %v", target, err)
		}
		if *check {
			current, err := os.ReadFile(target)
			if err != nil || !bytes.Equal(current, generated) {
				fatalf("generated asset artifact is stale: %s; run go generate .", target)
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			fatalf("create target directory: %v", err)
		}
		if err := os.WriteFile(target, generated, 0o644); err != nil {
			fatalf("write %s: %v", target, err)
		}
		fmt.Printf("generated %s\n", target)
	}
	if *check {
		fmt.Println("asset schema generated artifacts are current")
	}
}

func sortedTargets() []string {
	result := make([]string, 0, len(targets))
	for target := range targets {
		result = append(result, target)
	}
	sort.Strings(result)
	return result
}

func generateGo(schemas []AssetSchema) ([]byte, error) {
	var output strings.Builder
	output.WriteString("// Code generated by tools/schema-gen; DO NOT EDIT.\n")
	output.WriteString("package assetschema\n\n")
	output.WriteString("type EnumOption struct { Value any; Label string }\n")
	output.WriteString("type Field struct { Name, Label, Type, RequiredWhen, Group, Widget, Help string; Required, Searchable, Sortable, Filterable, Import, Export, List, Sensitive bool; MaxLength int; Minimum, Maximum *float64; Default any; Enum []EnumOption }\n")
	output.WriteString("type Schema struct { Type, Title, Compatibility, Migration, Table string; Version int; Fields []Field }\n\n")
	output.WriteString("var Types = map[string]Schema{\n")
	for _, schema := range schemas {
		fmt.Fprintf(&output, "%q: {Type:%q, Title:%q, Version:%d, Compatibility:%q, Migration:%q, Table:%q, Fields: []Field{\n",
			schema.Type, schema.Type, schema.Title, schema.Version, schema.Compatibility, schema.Migration, schema.Storage.Table)
		for _, field := range schema.Fields {
			fmt.Fprintf(&output, "{Name:%q, Label:%q, Type:%q, Required:%t, RequiredWhen:%q, MaxLength:%d, Searchable:%t, Sortable:%t, Filterable:%t, Import:%t, Export:%t, List:%t, Sensitive:%t, Group:%q, Widget:%q, Help:%q",
				field.Name, field.Label, field.Type, field.Required, field.RequiredWhen, field.MaxLength,
				field.Searchable, field.Sortable, field.Filterable, field.Import, field.Export,
				field.List, field.Sensitive, field.Group, field.Widget, field.Help)
			if field.Minimum != nil {
				fmt.Fprintf(&output, ", Minimum:float64Pointer(%s)", strconv.FormatFloat(*field.Minimum, 'f', -1, 64))
			}
			if field.Maximum != nil {
				fmt.Fprintf(&output, ", Maximum:float64Pointer(%s)", strconv.FormatFloat(*field.Maximum, 'f', -1, 64))
			}
			if field.Default != nil {
				fmt.Fprintf(&output, ", Default:%s", goLiteral(field.Default))
			}
			if len(field.Enum) > 0 {
				output.WriteString(", Enum:[]EnumOption{")
				for _, option := range field.Enum {
					fmt.Fprintf(&output, "{Value:%s, Label:%q},", goLiteral(option.Value), option.Label)
				}
				output.WriteString("}")
			}
			output.WriteString("},\n")
		}
		output.WriteString("}},\n")
	}
	output.WriteString("}\n\nfunc float64Pointer(value float64) *float64 { return &value }\n")
	return format.Source([]byte(output.String()))
}

func generateTypeScript(schemas []AssetSchema) ([]byte, error) {
	var output strings.Builder
	output.WriteString("// Code generated by tools/schema-gen; DO NOT EDIT.\n")
	output.WriteString("export type AssetType = ")
	for index, schema := range schemas {
		if index > 0 {
			output.WriteString(" | ")
		}
		fmt.Fprintf(&output, "%q", schema.Type)
	}
	output.WriteString("\n\n")
	for _, schema := range schemas {
		fmt.Fprintf(&output, "export interface %sAsset {\n", exportedName(schema.Type))
		for _, field := range schema.Fields {
			optional := "?"
			if field.Required {
				optional = ""
			}
			fmt.Fprintf(&output, "  %s%s: %s\n", field.Name, optional, tsType(field))
		}
		output.WriteString("}\n\n")
	}
	output.WriteString("export interface AssetByType {\n")
	for _, schema := range schemas {
		fmt.Fprintf(&output, "  %q: %sAsset\n", schema.Type, exportedName(schema.Type))
	}
	output.WriteString("}\n")
	return []byte(output.String()), nil
}

func generateVueMetadata(schemas []AssetSchema) ([]byte, error) {
	value, err := json.MarshalIndent(schemas, "", "  ")
	if err != nil {
		return nil, err
	}
	return append([]byte("// Code generated by tools/schema-gen; DO NOT EDIT.\nexport const assetSchemas = "), append(value, []byte(" as const\n")...)...), nil
}

func generateOpenAPI(schemas []AssetSchema) ([]byte, error) {
	var output strings.Builder
	output.WriteString("# Code generated by tools/schema-gen; DO NOT EDIT.\ncomponents:\n  schemas:\n")
	for _, schema := range schemas {
		fmt.Fprintf(&output, "    %sAsset:\n      type: object\n      additionalProperties: false\n", exportedName(schema.Type))
		var required []string
		for _, field := range schema.Fields {
			if field.Required {
				required = append(required, field.Name)
			}
		}
		if len(required) > 0 {
			fmt.Fprintf(&output, "      required: [%s]\n", strings.Join(required, ", "))
		}
		writeOpenAPIProperties(&output, schema.Fields)
		fmt.Fprintf(&output, "    %sAssetPatch:\n      type: object\n      additionalProperties: false\n", exportedName(schema.Type))
		writeOpenAPIProperties(&output, schema.Fields)
	}
	return []byte(output.String()), nil
}

func writeOpenAPIProperties(output *strings.Builder, fields []FieldSpec) {
	output.WriteString("      properties:\n")
	for _, field := range fields {
		fmt.Fprintf(output, "        %s:\n          type: %s\n", field.Name, openAPIType(field.Type))
		if field.Type == "date" {
			output.WriteString("          format: date\n")
		}
		if field.MaxLength > 0 {
			fmt.Fprintf(output, "          maxLength: %d\n", field.MaxLength)
		}
		if field.Minimum != nil {
			fmt.Fprintf(output, "          minimum: %s\n", strconv.FormatFloat(*field.Minimum, 'f', -1, 64))
		}
		if field.Maximum != nil {
			fmt.Fprintf(output, "          maximum: %s\n", strconv.FormatFloat(*field.Maximum, 'f', -1, 64))
		}
		if len(field.Enum) > 0 {
			var values []string
			for _, option := range field.Enum {
				values = append(values, fmt.Sprint(option.Value))
			}
			fmt.Fprintf(output, "          enum: [%s]\n", strings.Join(values, ", "))
		}
	}
}

func generateSQL(schemas []AssetSchema) ([]byte, error) {
	var output strings.Builder
	output.WriteString("-- Code generated by tools/schema-gen; DO NOT EDIT.\n")
	output.WriteString("CREATE SCHEMA IF NOT EXISTS asset;\n\n")
	for _, schema := range schemas {
		fmt.Fprintf(&output, "CREATE TABLE IF NOT EXISTS asset.%s (\n", quoteSQLIdentifier(schema.Storage.Table))
		output.WriteString("    id text PRIMARY KEY,\n    owner_id text NOT NULL,\n    department_id text,\n    version bigint NOT NULL DEFAULT 1,\n")
		output.WriteString("    created_at timestamptz NOT NULL DEFAULT now(),\n    updated_at timestamptz NOT NULL DEFAULT now(),\n    deleted_at timestamptz,\n")
		for index, field := range schema.Fields {
			fieldIdentifier := quoteSQLIdentifier(field.Name)
			fmt.Fprintf(&output, "    %s %s", fieldIdentifier, sqlType(field))
			if field.Required {
				output.WriteString(" NOT NULL")
			}
			if field.Default != nil {
				fmt.Fprintf(&output, " DEFAULT %s", sqlLiteral(field.Default))
			}
			if field.Minimum != nil {
				fmt.Fprintf(&output, " CHECK (%s >= %s)", fieldIdentifier, strconv.FormatFloat(*field.Minimum, 'f', -1, 64))
			}
			if field.Maximum != nil {
				fmt.Fprintf(&output, " CHECK (%s <= %s)", fieldIdentifier, strconv.FormatFloat(*field.Maximum, 'f', -1, 64))
			}
			if len(field.Enum) > 0 {
				var values []string
				for _, option := range field.Enum {
					values = append(values, sqlLiteral(option.Value))
				}
				fmt.Fprintf(&output, " CHECK (%s IN (%s))", fieldIdentifier, strings.Join(values, ", "))
			}
			if index < len(schema.Fields)-1 {
				output.WriteString(",")
			}
			output.WriteString("\n")
		}
		output.WriteString(");\n")
		fmt.Fprintf(&output, "CREATE INDEX IF NOT EXISTS %s_active_idx ON asset.%s (deleted_at, updated_at DESC);\n", schema.Storage.Table, quoteSQLIdentifier(schema.Storage.Table))
		for _, field := range schema.Fields {
			if field.Searchable || field.Filterable {
				fmt.Fprintf(&output, "CREATE INDEX IF NOT EXISTS %s_%s_idx ON asset.%s (%s);\n",
					schema.Storage.Table, field.Name, quoteSQLIdentifier(schema.Storage.Table), quoteSQLIdentifier(field.Name))
			}
		}
		output.WriteString("\n")
	}
	output.WriteString("CREATE TABLE IF NOT EXISTS asset.asset_versions (\n")
	output.WriteString("    asset_type varchar(64) NOT NULL,\n    asset_id text NOT NULL,\n")
	output.WriteString("    version bigint NOT NULL,\n    action varchar(20) NOT NULL,\n")
	output.WriteString("    changed_by text NOT NULL,\n    snapshot jsonb NOT NULL,\n")
	output.WriteString("    created_at timestamptz NOT NULL DEFAULT now(),\n")
	output.WriteString("    PRIMARY KEY (asset_type, asset_id, version)\n);\n")
	output.WriteString("CREATE INDEX IF NOT EXISTS asset_versions_asset_idx ON asset.asset_versions (asset_type, asset_id, version DESC);\n")
	return []byte(output.String()), nil
}

func goLiteral(value any) string {
	switch typed := value.(type) {
	case string:
		return strconv.Quote(typed)
	case int:
		return strconv.Itoa(typed)
	case float64:
		return strconv.FormatFloat(typed, 'f', -1, 64)
	case bool:
		return strconv.FormatBool(typed)
	default:
		return fmt.Sprintf("%#v", value)
	}
}

func sqlLiteral(value any) string {
	switch typed := value.(type) {
	case string:
		return "'" + strings.ReplaceAll(typed, "'", "''") + "'"
	default:
		return fmt.Sprint(value)
	}
}

func quoteSQLIdentifier(value string) string {
	return `"` + strings.ReplaceAll(value, `"`, `""`) + `"`
}

func sqlType(field FieldSpec) string {
	switch field.Type {
	case "string":
		if field.MaxLength > 0 {
			return fmt.Sprintf("varchar(%d)", field.MaxLength)
		}
		return "text"
	case "integer":
		return "bigint"
	case "number":
		return "numeric(18, 2)"
	case "boolean":
		return "boolean"
	case "date":
		return "date"
	default:
		panic("validated field type")
	}
}

func openAPIType(value string) string {
	switch value {
	case "date":
		return "string"
	case "number":
		return "number"
	default:
		return value
	}
}

func tsType(field FieldSpec) string {
	if len(field.Enum) > 0 {
		var values []string
		for _, option := range field.Enum {
			switch value := option.Value.(type) {
			case string:
				values = append(values, strconv.Quote(value))
			default:
				values = append(values, fmt.Sprint(value))
			}
		}
		return strings.Join(values, " | ")
	}
	switch field.Type {
	case "integer", "number":
		return "number"
	case "boolean":
		return "boolean"
	default:
		return "string"
	}
}

func exportedName(value string) string {
	parts := strings.Split(value, "-")
	for index := range parts {
		parts[index] = strings.ToUpper(parts[index][:1]) + parts[index][1:]
	}
	return strings.Join(parts, "")
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
