package main

import (
	"bytes"
	"crypto/sha256"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

const (
	sourcePath = "api/openapi/v1.yaml"
	targetPath = "platform/internal/contract/routes_gen.go"
)

var pathLine = regexp.MustCompile(`^  (/[^:]+):\s*$`)

func main() {
	write := flag.Bool("write", false, "write generated contract artifact")
	check := flag.Bool("check", false, "fail when generated artifact is stale")
	flag.Parse()
	if *write == *check {
		fatalf("choose exactly one of -write or -check")
	}

	source, err := os.ReadFile(sourcePath)
	if err != nil {
		fatalf("read source: %v", err)
	}
	generated, err := generate(source)
	if err != nil {
		fatalf("generate: %v", err)
	}
	if *check {
		current, err := os.ReadFile(targetPath)
		if err != nil || !bytes.Equal(current, generated) {
			fatalf("generated contract is stale; run go generate .")
		}
		fmt.Println("OpenAPI generated contract is current")
		return
	}
	if err := os.MkdirAll(filepath.Dir(targetPath), 0o755); err != nil {
		fatalf("create target directory: %v", err)
	}
	if err := os.WriteFile(targetPath, generated, 0o644); err != nil {
		fatalf("write target: %v", err)
	}
	fmt.Printf("generated %s\n", targetPath)
}

func generate(source []byte) ([]byte, error) {
	var routes []string
	for _, line := range strings.Split(string(source), "\n") {
		if match := pathLine.FindStringSubmatch(strings.TrimRight(line, "\r")); match != nil {
			routes = append(routes, match[1])
		}
	}
	if len(routes) == 0 {
		return nil, fmt.Errorf("no OpenAPI paths found")
	}
	sort.Strings(routes)
	sum := sha256.Sum256(source)
	var output strings.Builder
	output.WriteString("// Code generated by tools/contractgen; DO NOT EDIT.\n")
	output.WriteString("package contract\n\n")
	fmt.Fprintf(&output, "const OpenAPISHA256 = %q\n\n", fmt.Sprintf("%x", sum))
	output.WriteString("var PublicRoutes = []string{\n")
	for _, route := range routes {
		fmt.Fprintf(&output, "\t%q,\n", route)
	}
	output.WriteString("}\n")
	return format.Source([]byte(output.String()))
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
