// Code generated by tools/contractgen; DO NOT EDIT.
package contract

const OpenAPISHA256 = "6ca6083ea3cefb35b6b1fbf6568a50d2811c727f1e7577e020c00076c3011f01"

var PublicRoutes = []string{
	"/asset-types",
	"/asset-types/{type}/schema",
	"/assets/{type}",
	"/assets/{type}/{id}",
	"/assets/{type}/{id}/restore",
	"/assets/{type}/{id}/versions",
	"/auth/authorize",
	"/auth/change-password",
	"/auth/login",
	"/auth/logout",
	"/auth/me",
	"/auth/refresh",
	"/departments",
	"/export-jobs",
	"/health/live",
	"/health/ready",
	"/import-jobs",
	"/reporting/{report}",
	"/risks/{riskId}",
	"/users",
	"/users/{id}/access",
	"/workflows/{workflow}",
}
