// Code generated by tools/contractgen; DO NOT EDIT.
package contract

const OpenAPISHA256 = "97dd2d8456938c1696890ca817edc229924b0f753594b03dcda8365870be6bd2"

var PublicRoutes = []string{
	"/asset-types",
	"/asset-types/{type}/schema",
	"/assets/{type}",
	"/assets/{type}/{id}",
	"/assets/{type}/{id}/restore",
	"/auth/login",
	"/auth/logout",
	"/auth/me",
	"/auth/refresh",
	"/export-jobs",
	"/health/live",
	"/health/ready",
	"/import-jobs",
	"/reporting/{report}",
	"/risks/{riskId}",
	"/workflows/{workflow}",
}
