-- Code generated by tools/schema-gen; DO NOT EDIT.
CREATE SCHEMA IF NOT EXISTS asset;

CREATE TABLE IF NOT EXISTS asset."data_assets" (
    id text PRIMARY KEY,
    owner_id text NOT NULL,
    department_id text,
    version bigint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    "source_system" varchar(200) NOT NULL,
    "security_level" bigint CHECK ("security_level" IN (0, 1, 2)),
    "is_critical_infra" boolean DEFAULT false,
    "data_name" varchar(200) NOT NULL,
    "data_items" text NOT NULL,
    "data_classification" bigint CHECK ("data_classification" IN (0, 1, 2, 3, 4)),
    "data_carrier" varchar(100) NOT NULL,
    "data_source" bigint CHECK ("data_source" IN (0, 1)),
    "data_size" numeric(18, 2) CHECK ("data_size" >= 0),
    "data_count" bigint CHECK ("data_count" >= 0),
    "processor_name" varchar(200) NOT NULL,
    "main_leader" varchar(50) NOT NULL,
    "security_leader" varchar(50) NOT NULL,
    "contact_phone" varchar(50) NOT NULL,
    "processing_purpose" text NOT NULL,
    "usage_scope" text NOT NULL,
    "sharing_scope" text,
    "cross_border" boolean DEFAULT false,
    "has_personal_info_elements" boolean DEFAULT false,
    "personal_info_scale" bigint CHECK ("personal_info_scale" >= 0),
    "has_sensitive_personal" boolean DEFAULT false,
    "has_name" boolean DEFAULT false,
    "has_contact" boolean DEFAULT false,
    "is_cross_border" boolean DEFAULT false,
    "has_cross_border_assessment" boolean DEFAULT false,
    "assessment_result" varchar(100),
    "security_measures" text NOT NULL,
    "remarks" text
);
CREATE INDEX IF NOT EXISTS data_assets_active_idx ON asset."data_assets" (deleted_at, updated_at DESC);
CREATE INDEX IF NOT EXISTS data_assets_source_system_idx ON asset."data_assets" ("source_system");
CREATE INDEX IF NOT EXISTS data_assets_security_level_idx ON asset."data_assets" ("security_level");
CREATE INDEX IF NOT EXISTS data_assets_is_critical_infra_idx ON asset."data_assets" ("is_critical_infra");
CREATE INDEX IF NOT EXISTS data_assets_data_name_idx ON asset."data_assets" ("data_name");
CREATE INDEX IF NOT EXISTS data_assets_data_classification_idx ON asset."data_assets" ("data_classification");
CREATE INDEX IF NOT EXISTS data_assets_data_carrier_idx ON asset."data_assets" ("data_carrier");
CREATE INDEX IF NOT EXISTS data_assets_data_source_idx ON asset."data_assets" ("data_source");
CREATE INDEX IF NOT EXISTS data_assets_processor_name_idx ON asset."data_assets" ("processor_name");
CREATE INDEX IF NOT EXISTS data_assets_cross_border_idx ON asset."data_assets" ("cross_border");
CREATE INDEX IF NOT EXISTS data_assets_has_personal_info_elements_idx ON asset."data_assets" ("has_personal_info_elements");
CREATE INDEX IF NOT EXISTS data_assets_has_sensitive_personal_idx ON asset."data_assets" ("has_sensitive_personal");

CREATE TABLE IF NOT EXISTS asset."hardware_software_assets" (
    id text PRIMARY KEY,
    owner_id text NOT NULL,
    department_id text,
    version bigint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    "asset_name" varchar(200) NOT NULL,
    "category" varchar(100) NOT NULL,
    "brand" varchar(100) NOT NULL,
    "model" varchar(100) NOT NULL,
    "quantity" bigint NOT NULL CHECK ("quantity" >= 1),
    "department" varchar(100) NOT NULL,
    "responsible_person" varchar(50) NOT NULL,
    "user" varchar(50),
    "location" varchar(200) NOT NULL,
    "use_status" bigint NOT NULL CHECK ("use_status" IN (0, 1, 2, 3)),
    "device_status" bigint CHECK ("device_status" IN (0, 1, 2)),
    "network" varchar(100) NOT NULL,
    "ip_address" varchar(50),
    "mac_address" varchar(50),
    "os_version" varchar(100),
    "start_use_date" date NOT NULL,
    "warranty_end_date" date,
    "asset_life" varchar(50) NOT NULL,
    "supplier" varchar(200),
    "remarks" text
);
CREATE INDEX IF NOT EXISTS hardware_software_assets_active_idx ON asset."hardware_software_assets" (deleted_at, updated_at DESC);
CREATE INDEX IF NOT EXISTS hardware_software_assets_asset_name_idx ON asset."hardware_software_assets" ("asset_name");
CREATE INDEX IF NOT EXISTS hardware_software_assets_category_idx ON asset."hardware_software_assets" ("category");
CREATE INDEX IF NOT EXISTS hardware_software_assets_brand_idx ON asset."hardware_software_assets" ("brand");
CREATE INDEX IF NOT EXISTS hardware_software_assets_model_idx ON asset."hardware_software_assets" ("model");
CREATE INDEX IF NOT EXISTS hardware_software_assets_department_idx ON asset."hardware_software_assets" ("department");
CREATE INDEX IF NOT EXISTS hardware_software_assets_location_idx ON asset."hardware_software_assets" ("location");
CREATE INDEX IF NOT EXISTS hardware_software_assets_use_status_idx ON asset."hardware_software_assets" ("use_status");
CREATE INDEX IF NOT EXISTS hardware_software_assets_device_status_idx ON asset."hardware_software_assets" ("device_status");
CREATE INDEX IF NOT EXISTS hardware_software_assets_network_idx ON asset."hardware_software_assets" ("network");
CREATE INDEX IF NOT EXISTS hardware_software_assets_ip_address_idx ON asset."hardware_software_assets" ("ip_address");
CREATE INDEX IF NOT EXISTS hardware_software_assets_mac_address_idx ON asset."hardware_software_assets" ("mac_address");
CREATE INDEX IF NOT EXISTS hardware_software_assets_os_version_idx ON asset."hardware_software_assets" ("os_version");
CREATE INDEX IF NOT EXISTS hardware_software_assets_supplier_idx ON asset."hardware_software_assets" ("supplier");

CREATE TABLE IF NOT EXISTS asset."responsible_department_assets" (
    id text PRIMARY KEY,
    owner_id text NOT NULL,
    department_id text,
    version bigint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    "department_name" varchar(100) NOT NULL,
    "department_code" varchar(50),
    "department_head" varchar(50),
    "head_phone" varchar(50),
    "department_fax" varchar(50),
    "remarks" text
);
CREATE INDEX IF NOT EXISTS responsible_department_assets_active_idx ON asset."responsible_department_assets" (deleted_at, updated_at DESC);
CREATE INDEX IF NOT EXISTS responsible_department_assets_department_name_idx ON asset."responsible_department_assets" ("department_name");
CREATE INDEX IF NOT EXISTS responsible_department_assets_department_code_idx ON asset."responsible_department_assets" ("department_code");
CREATE INDEX IF NOT EXISTS responsible_department_assets_department_head_idx ON asset."responsible_department_assets" ("department_head");

CREATE TABLE IF NOT EXISTS asset."software_statistics_assets" (
    id text PRIMARY KEY,
    owner_id text NOT NULL,
    department_id text,
    version bigint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    "report_year" bigint NOT NULL CHECK ("report_year" >= 2000) CHECK ("report_year" <= 2100),
    "department_name" varchar(100) NOT NULL,
    "department_head" varchar(50),
    "head_phone" varchar(50),
    "department_fax" varchar(50),
    "registration_date" date,
    "is_legalization_done" boolean DEFAULT false,
    "total_staff_count" bigint CHECK ("total_staff_count" >= 0),
    "computer_user_count" bigint CHECK ("computer_user_count" >= 0),
    "server_count" bigint CHECK ("server_count" >= 0),
    "desktop_count" bigint CHECK ("desktop_count" >= 0),
    "laptop_count" bigint CHECK ("laptop_count" >= 0),
    "pur_os_dom_lic" bigint CHECK ("pur_os_dom_lic" >= 0),
    "pur_os_dom_amt" numeric(18, 2) CHECK ("pur_os_dom_amt" >= 0),
    "pur_os_for_lic" bigint CHECK ("pur_os_for_lic" >= 0),
    "pur_os_for_amt" numeric(18, 2) CHECK ("pur_os_for_amt" >= 0),
    "pur_office_dom_lic" bigint CHECK ("pur_office_dom_lic" >= 0),
    "pur_office_dom_amt" numeric(18, 2) CHECK ("pur_office_dom_amt" >= 0),
    "pur_office_for_lic" bigint CHECK ("pur_office_for_lic" >= 0),
    "pur_office_for_amt" numeric(18, 2) CHECK ("pur_office_for_amt" >= 0),
    "pur_av_dom_lic" bigint CHECK ("pur_av_dom_lic" >= 0),
    "pur_av_dom_amt" numeric(18, 2) CHECK ("pur_av_dom_amt" >= 0),
    "pur_av_for_lic" bigint CHECK ("pur_av_for_lic" >= 0),
    "pur_av_for_amt" numeric(18, 2) CHECK ("pur_av_for_amt" >= 0),
    "cum_os_dom_lic" bigint CHECK ("cum_os_dom_lic" >= 0),
    "cum_os_for_lic" bigint CHECK ("cum_os_for_lic" >= 0),
    "cum_office_dom_lic" bigint CHECK ("cum_office_dom_lic" >= 0),
    "cum_office_for_lic" bigint CHECK ("cum_office_for_lic" >= 0),
    "cum_av_dom_lic" bigint CHECK ("cum_av_dom_lic" >= 0),
    "cum_av_for_lic" bigint CHECK ("cum_av_for_lic" >= 0),
    "modification_log" text
);
CREATE INDEX IF NOT EXISTS software_statistics_assets_active_idx ON asset."software_statistics_assets" (deleted_at, updated_at DESC);
CREATE INDEX IF NOT EXISTS software_statistics_assets_report_year_idx ON asset."software_statistics_assets" ("report_year");
CREATE INDEX IF NOT EXISTS software_statistics_assets_department_name_idx ON asset."software_statistics_assets" ("department_name");
CREATE INDEX IF NOT EXISTS software_statistics_assets_is_legalization_done_idx ON asset."software_statistics_assets" ("is_legalization_done");

CREATE TABLE IF NOT EXISTS asset."supply_chain_assets" (
    id text PRIMARY KEY,
    owner_id text NOT NULL,
    department_id text,
    version bigint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    "system_name" varchar(200) NOT NULL,
    "supplier_type" bigint NOT NULL CHECK ("supplier_type" IN (0, 1, 2, 3, 4, 5, 6, 7, 8)),
    "company_name" varchar(200) NOT NULL,
    "province_city" varchar(100) NOT NULL,
    "address" varchar(300) NOT NULL,
    "contact_person" varchar(50) NOT NULL,
    "contact_phone" varchar(50) NOT NULL,
    "service_content" text NOT NULL,
    "remarks" text
);
CREATE INDEX IF NOT EXISTS supply_chain_assets_active_idx ON asset."supply_chain_assets" (deleted_at, updated_at DESC);
CREATE INDEX IF NOT EXISTS supply_chain_assets_system_name_idx ON asset."supply_chain_assets" ("system_name");
CREATE INDEX IF NOT EXISTS supply_chain_assets_supplier_type_idx ON asset."supply_chain_assets" ("supplier_type");
CREATE INDEX IF NOT EXISTS supply_chain_assets_company_name_idx ON asset."supply_chain_assets" ("company_name");
CREATE INDEX IF NOT EXISTS supply_chain_assets_province_city_idx ON asset."supply_chain_assets" ("province_city");

CREATE TABLE IF NOT EXISTS asset."system_info_assets" (
    id text PRIMARY KEY,
    owner_id text NOT NULL,
    department_id text,
    version bigint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    "system_name" varchar(200) NOT NULL,
    "subsystems" text,
    "deploy_location" varchar(200) NOT NULL,
    "network_name" varchar(100) NOT NULL,
    "network_type" bigint NOT NULL CHECK ("network_type" IN (0, 1, 2)),
    "run_status" bigint NOT NULL CHECK ("run_status" IN (0, 1, 2, 3, 4)),
    "build_time" date NOT NULL,
    "has_media_platform" boolean DEFAULT false,
    "mobile_app_type" bigint CHECK ("mobile_app_type" IN (0, 1, 2, 3, 4)),
    "domain_or_ip" varchar(200) NOT NULL,
    "function_modules" text,
    "has_external_interface" boolean DEFAULT false,
    "interface_scope" text,
    "supervisory_dept" varchar(100) NOT NULL,
    "app_responsible_dept" varchar(100) NOT NULL,
    "network_responsible_dept" varchar(100) NOT NULL,
    "maintenance_mode" bigint NOT NULL CHECK ("maintenance_mode" IN (0, 1, 2)),
    "construction_dept" varchar(100) NOT NULL,
    "maintenance_vendor" varchar(100),
    "integration_vendor" varchar(100),
    "development_vendor" varchar(100),
    "system_contact" varchar(100) NOT NULL,
    "security_contact" varchar(100) NOT NULL,
    "admin_contact" varchar(100) NOT NULL,
    "data_content" text NOT NULL,
    "has_personal_info" boolean DEFAULT false,
    "important_data_risk" varchar(200),
    "data_storage_location" varchar(100) NOT NULL,
    "has_cloud_deploy" boolean DEFAULT false,
    "cloud_provider" varchar(100),
    "cloud_security_review" bigint CHECK ("cloud_security_review" IN (0, 1, 2, 3)),
    "security_level" bigint NOT NULL CHECK ("security_level" IN (0, 1, 2, 3)),
    "security_record_no" varchar(100),
    "security_assessment" bigint CHECK ("security_assessment" IN (0, 1, 2, 3)),
    "crypto_assessment" bigint CHECK ("crypto_assessment" IN (0, 1, 2, 3)),
    "backup_type" bigint NOT NULL CHECK ("backup_type" IN (0, 1, 2, 3)),
    "log_retention" varchar(50) NOT NULL,
    "security_devices" text,
    "network_devices" text,
    "os_info" text,
    "database_info" text,
    "middleware_info" text,
    "dev_framework" text,
    "third_party_components" text,
    "computing_rental" text,
    "remarks" text
);
CREATE INDEX IF NOT EXISTS system_info_assets_active_idx ON asset."system_info_assets" (deleted_at, updated_at DESC);
CREATE INDEX IF NOT EXISTS system_info_assets_system_name_idx ON asset."system_info_assets" ("system_name");
CREATE INDEX IF NOT EXISTS system_info_assets_deploy_location_idx ON asset."system_info_assets" ("deploy_location");
CREATE INDEX IF NOT EXISTS system_info_assets_network_name_idx ON asset."system_info_assets" ("network_name");
CREATE INDEX IF NOT EXISTS system_info_assets_network_type_idx ON asset."system_info_assets" ("network_type");
CREATE INDEX IF NOT EXISTS system_info_assets_run_status_idx ON asset."system_info_assets" ("run_status");
CREATE INDEX IF NOT EXISTS system_info_assets_has_media_platform_idx ON asset."system_info_assets" ("has_media_platform");
CREATE INDEX IF NOT EXISTS system_info_assets_mobile_app_type_idx ON asset."system_info_assets" ("mobile_app_type");
CREATE INDEX IF NOT EXISTS system_info_assets_domain_or_ip_idx ON asset."system_info_assets" ("domain_or_ip");
CREATE INDEX IF NOT EXISTS system_info_assets_has_external_interface_idx ON asset."system_info_assets" ("has_external_interface");
CREATE INDEX IF NOT EXISTS system_info_assets_supervisory_dept_idx ON asset."system_info_assets" ("supervisory_dept");
CREATE INDEX IF NOT EXISTS system_info_assets_app_responsible_dept_idx ON asset."system_info_assets" ("app_responsible_dept");
CREATE INDEX IF NOT EXISTS system_info_assets_network_responsible_dept_idx ON asset."system_info_assets" ("network_responsible_dept");
CREATE INDEX IF NOT EXISTS system_info_assets_maintenance_mode_idx ON asset."system_info_assets" ("maintenance_mode");
CREATE INDEX IF NOT EXISTS system_info_assets_has_personal_info_idx ON asset."system_info_assets" ("has_personal_info");
CREATE INDEX IF NOT EXISTS system_info_assets_data_storage_location_idx ON asset."system_info_assets" ("data_storage_location");
CREATE INDEX IF NOT EXISTS system_info_assets_has_cloud_deploy_idx ON asset."system_info_assets" ("has_cloud_deploy");
CREATE INDEX IF NOT EXISTS system_info_assets_cloud_security_review_idx ON asset."system_info_assets" ("cloud_security_review");
CREATE INDEX IF NOT EXISTS system_info_assets_security_level_idx ON asset."system_info_assets" ("security_level");
CREATE INDEX IF NOT EXISTS system_info_assets_security_assessment_idx ON asset."system_info_assets" ("security_assessment");
CREATE INDEX IF NOT EXISTS system_info_assets_crypto_assessment_idx ON asset."system_info_assets" ("crypto_assessment");
CREATE INDEX IF NOT EXISTS system_info_assets_backup_type_idx ON asset."system_info_assets" ("backup_type");

CREATE TABLE IF NOT EXISTS asset."vulnerability_assets" (
    id text PRIMARY KEY,
    owner_id text NOT NULL,
    department_id text,
    version bigint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    "system_name" varchar(200) NOT NULL,
    "discovery_date" date NOT NULL,
    "discovery_method" bigint CHECK ("discovery_method" IN (0, 1, 2)),
    "affected_device" text NOT NULL,
    "vulnerability_name" varchar(200) NOT NULL,
    "cve_number" varchar(50),
    "cnvd_number" varchar(50),
    "domain" varchar(200),
    "ip_address" varchar(50),
    "severity" bigint NOT NULL CHECK ("severity" IN (0, 1, 2)),
    "protocol" varchar(20),
    "port" bigint CHECK ("port" >= 0) CHECK ("port" <= 65535),
    "vuln_type" varchar(100),
    "risk_description" text NOT NULL,
    "risk_impact" text NOT NULL,
    "remediation_suggestion" text NOT NULL,
    "remediation_measure" text,
    "completion_date" date
);
CREATE INDEX IF NOT EXISTS vulnerability_assets_active_idx ON asset."vulnerability_assets" (deleted_at, updated_at DESC);
CREATE INDEX IF NOT EXISTS vulnerability_assets_system_name_idx ON asset."vulnerability_assets" ("system_name");
CREATE INDEX IF NOT EXISTS vulnerability_assets_discovery_date_idx ON asset."vulnerability_assets" ("discovery_date");
CREATE INDEX IF NOT EXISTS vulnerability_assets_discovery_method_idx ON asset."vulnerability_assets" ("discovery_method");
CREATE INDEX IF NOT EXISTS vulnerability_assets_vulnerability_name_idx ON asset."vulnerability_assets" ("vulnerability_name");
CREATE INDEX IF NOT EXISTS vulnerability_assets_cve_number_idx ON asset."vulnerability_assets" ("cve_number");
CREATE INDEX IF NOT EXISTS vulnerability_assets_cnvd_number_idx ON asset."vulnerability_assets" ("cnvd_number");
CREATE INDEX IF NOT EXISTS vulnerability_assets_ip_address_idx ON asset."vulnerability_assets" ("ip_address");
CREATE INDEX IF NOT EXISTS vulnerability_assets_severity_idx ON asset."vulnerability_assets" ("severity");
CREATE INDEX IF NOT EXISTS vulnerability_assets_protocol_idx ON asset."vulnerability_assets" ("protocol");
CREATE INDEX IF NOT EXISTS vulnerability_assets_vuln_type_idx ON asset."vulnerability_assets" ("vuln_type");

CREATE TABLE IF NOT EXISTS asset.asset_versions (
    asset_type varchar(64) NOT NULL,
    asset_id text NOT NULL,
    version bigint NOT NULL,
    action varchar(20) NOT NULL,
    changed_by text NOT NULL,
    snapshot jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (asset_type, asset_id, version)
);
CREATE INDEX IF NOT EXISTS asset_versions_asset_idx ON asset.asset_versions (asset_type, asset_id, version DESC);
